redis:
  singleton: {host: 127.0.0.1, port: 6379}
  cluster:
  - {host: 123, port: 123}
  - {host: 123, port: 123}
  
  
detectron:
   cfg: configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml 
   wts: detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
