cfg: ../../../3rdparts/Detectron/configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml
weights: /tmp/detectron-download-cache/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl
out_when_no_box: 0
thresh: 0.7
kp_thresh: 2.0

